apiVersion: v1
kind: Service
metadata:
  name: hello-deploy
  labels:
    app: hello
spec:
  type: NodePort
  selector:
    app: hello
  ports:
    - name: http
      port: 80
      targetPort: 80
      # nodePort: 30080  # (opcjonalnie: odkomentuj, aby wymusić konkretny port)
